export const label = {
  description: 'Описание',
  tabs: {
    main: 'Главная',
    myProfile: 'Профиль',
    approveAnnouncements: 'Модерация',
    messages: 'Сообщения',
    announcements: 'Объявления',
    products: 'Продукты',
    cards: 'Карточки',
    contacts: 'Контакты'
  },
  help: 'Помощь',
  welcomeToVavilon: 'Добро пожаловать в Vavilon',
  pleaseLogin: 'Пожалуйста войдите в аккаунт',
  labelPleaseFillAllTheFieldsForSignUp: 'Пожалуйста заполните все поля регистрации',
  pleaseEnterTheCodeWhichIsSentOnEmail: 'Пожалуйста введите код отправленный на ящик',
  thisFieldIs: 'Поле',
  required: 'обязательно',
  login: 'Логин',
  password: 'Пароль',
  code: 'Код',
  firstName: 'Имя',
  lastName: 'Фамилия',
  email: 'Емайл',
  theEmailIs: 'Емайл',
  incorrect: 'неверный',
  minimumLengthOfPasswordIsBetween: 'и длинна пароля должна быть от 6 до 18',
  signIn: 'Войти в аккаунт',
  forgotThePassword: 'Забыли пароль?',
  signUp: 'Регистрация',
  submit: 'Отправить',
  content: 'Контент',
  priceStart: 'Минимальная цена',
  priceEnd: 'Максимальная цена',
  currencySign: 'Валюта',
  sortBy: 'Сортировка',
  direction: 'Возрастанию/Убыванию',
  search: 'Поиск',
  save: 'Сохранить',
  close: 'Закрыть',
  readyForReview: 'Готово для модерации',
  moderationStatus: 'Статус модерации',
  selectContacts: '[Выбрать контакты]',
  selectAnnouncementType: '[Выбрать тип объявления]',
  selectMeasure: '[Выбрать объем]',
  addProduct: 'Добавить продукт',
  select: 'Выбрать',
  price: 'Цена',
  selectCurrencySign: '[Выбрать валюту]',
  markTerritoryForDelivery: 'Обозначте территорию для доставки',
  volume: 'Объем',
  edit: 'Изменить',
  addAnnouncement: 'Добавить объявление',
  deleteSelectedAnnouncements: 'Удалить выбранные объявления',
  addContact: 'Добавить контакты',
  deleteSelectedContacts: 'Удалить выбранные контакты',
  name: 'Имя',
  contactType: 'Тип контакта',
  value: 'Значение',
  contactDetails: 'Контактная иформация',
  contactName: 'Имя контакта',
  announcement: 'Объявление',
  sellerProfile: 'Профиль продавца',
  chat: 'Чат',
  selectModerationStatus: '[Выбрать статус модерации]',
  updateModerationStatus: 'Изменить статус модерации',
  copy: 'Скопировать',
  territoryForDelivery: 'Территория доставки',
  comment: 'Комментарий',
  rated: 'Оценил',
  reply: 'Ответить',
  more: 'БОЛЬШЕ',
  messages: 'Сообщения',
  chatWith: 'Чат с',
  send: 'Отправить',
  deleteSelectedProducts: 'Удалить выбранные продукты',
  productDetails: 'Информация о продукте',
  productName: 'Имя продукта',
  selectProductCategory: '[Выбрать категорию продукта]',
  uploadImages: 'Загрузить фото',
  mainImage: 'Главная',
  delete: 'Удалить',
  info: 'Информация',
  comments: 'Комментарий',
  averageRate: 'Средняя оценка',
  announcements: 'Объявлений',
  addCard: 'Добавить карточку',
  deleteSelectedCards: 'Удалить выбранные карточки',
  action: 'Действие',
  userType: 'Тип пользователя',
  userCardDetails: 'Информация о карточке',
  cardName: 'Имя карточки',
  actionType: 'Тип действий',
  inn: 'ИНН',
  msgAreYouSureYouWantToDeleteSelectedAnnouncements: 'Вы уверены что вы хотите удалить выбранные объявления?',
  msgAreYouSureYouWantToDeleteSelectedContacts: 'Вы уверены что вы хотите удалить выбранные контакты?',
  msgAreYouSureYouWantToDeleteSelectedProducts: 'Вы уверены что вы хотите удалить выбранные продукты?<br>ВНИМАНИЕ: Объявления с выбранными продуктами так же будут удалены!',
  msgAreYouSureYouWantToDeleteSelectedCards: 'Вы уверены что вы хотите удалить выбранные карточки?',
  msgInvalidPassword: 'Поле <strong>обязательно</strong> минимальная длина пароля 6 и максимальная 18 так же пароль должен содержать хотя бы 1 букву и цифру',
  confirmPassword: 'Подтвердить пароль',
  msgPasswordsAreNotTheSame: 'Пароли не совпадают',
  loginOrEmail: 'Логин или Email',
  noResult: 'Ничего не найдено',

  sortDirections: {
    ASC: 'Возрастанию',
    DESC: 'Убыванию'
  },
  sortOptions: {
    rating: 'Рейтинг',
    price: 'Цена',
    productName: 'Имя продукта'
  },
  reset: 'Сбросить',
  enterAnEmailAndReceiveTheLink: 'Укажите свой email что бы получить ссылку для восстановления пароля',
  msgCookiesAreDisabled: 'Согласно настройкам вашего браузера мы не можем хранить cookies. ' +
    '<br>Это значит что вы не сможете использовать свой аккаунт. ' +
    '<br>Пожалуйста если вы хотите войти в ваш аккаунт - разрешите нам хранить файлы cookies' +
    '<br>Как сделать это в браузере chrome - <a target="_blank" href="https://support.google.com/accounts/answer/61416?hl=en&co=GENIE.Platform%3DDesktop">ссылка</a>',
  getLinkForRestoringPassword: 'Получить ссылку для восстановления пароля',
  msgRestorePasswordLinkIsSendOnTheEmail: 'Ссылка для восстановления пароля отправлена на ваш email. Пожалуйста используйте её для восстановления пароля',
  resetPassword: 'Изменить пароль',
  labelHome: 'Главная',
  labelAnnouncements: 'Объявления',
  notRated: 'Нет оценок',
  newPassword: 'Новый пароль',
  pleaseEnterYourNewPasswordBelow: 'Пожалуйста введите ваш новый пароль'
}
