export const label = {
  description: 'Description',
  tabs: {
    main: 'Main',
    myProfile: 'My profile',
    approveAnnouncements: 'Approve Announcements',
    messages: 'Messages',
    announcements: 'Announcements',
    products: 'Products',
    cards: 'Cards',
    contacts: 'Contacts'
  },
  help: 'help',
  welcomeToVavilon: 'Welcome to Vavilon',
  pleaseLogin: 'Please sign in',
  labelPleaseFillAllTheFieldsForSignUp: 'Please fill all the fields for signing up',
  pleaseEnterTheCodeWhichIsSentOnEmail: 'Please enter the code which is sent on email',
  thisFieldIs: 'This field is',
  required: 'required',
  login: 'Login',
  password: 'Password',
  code: 'Code',
  firstName: 'First name',
  lastName: 'Last name',
  email: 'Email',
  theEmailIs: 'The email is',
  incorrect: 'incorrect',
  minimumLengthOfPasswordIsBetween: 'and minimum length of password is 6 and maximum is 18',
  signIn: 'Sign in',
  forgotThePassword: 'Forgot the password?',
  signUp: 'Sign up',
  submit: 'Submit',
  content: 'Content',
  priceStart: 'Price start',
  priceEnd: 'Price end',
  currencySign: 'Currency sign',
  sortBy: 'Sort by',
  direction: 'Direction',
  search: 'Search',
  save: 'Save',
  close: 'Close',
  readyForReview: 'Ready for review',
  moderationStatus: 'Moderation status',
  selectContacts: '[Select contacts]',
  selectAnnouncementType: '[Select announcement type]',
  selectMeasure: '[Select measure]',
  addProduct: 'Add product',
  select: 'Select',
  price: 'Price',
  selectCurrencySign: '[Select currency sign]',
  markTerritoryForDelivery: 'Mark territory for delivery',
  volume: 'Volume',
  edit: 'Edit',
  addAnnouncement: 'Add announcement',
  deleteSelectedAnnouncements: 'Delete selected announcements',
  addContact: 'Add contact',
  deleteSelectedContacts: 'Delete selected contacts',
  name: 'Name',
  contactType: 'Contact type',
  value: 'Value',
  contactDetails: 'Contact details',
  contactName: 'Contact name',
  announcement: 'Announcement',
  sellerProfile: 'Seller profile',
  chat: 'Chat',
  selectModerationStatus: '[Select moderation status]',
  updateModerationStatus: 'Update moderation status',
  copy: 'Copy',
  territoryForDelivery: 'Territory for delivery',
  comment: 'Comment',
  rated: 'Rated',
  reply: 'Reply',
  more: 'MORE',
  messages: 'Messages',
  chatWith: 'Chat with',
  send: 'Send',
  deleteSelectedProducts: 'Delete selected products',
  productDetails: 'Product details',
  productName: 'Product name',
  selectProductCategory: '[Select product category]',
  uploadImages: 'Upload images',
  mainImage: 'Main',
  delete: 'Delete',
  info: 'Info',
  comments: 'Comments',
  averageRate: 'Average rate',
  announcements: 'Announcements',
  addCard: 'Add card',
  deleteSelectedCards: 'Delete selected cards',
  action: 'Action',
  userType: 'User type',
  userCardDetails: 'User card details',
  cardName: 'Card name',
  actionType: 'Action type',
  inn: 'INN',
  msgAreYouSureYouWantToDeleteSelectedAnnouncements: 'Are you sure you want to delete selected announcements?',
  msgAreYouSureYouWantToDeleteSelectedContacts: 'Are you sure you want to delete selected contacts?',
  msgAreYouSureYouWantToDeleteSelectedProducts: 'Are you sure you want to delete selected products?<br>NOTE: it will also delete announcements with selected products!',
  msgAreYouSureYouWantToDeleteSelectedCards: 'Are you sure you want to delete selected cards?'
}
