export const label = {
  description: 'Описание',
  tabs: {
    main: 'Главная',
    myProfile: 'Профиль',
    approveAnnouncements: 'Модерация',
    messages: 'Сообщения',
    announcements: 'Объявления',
    products: 'Продукты',
    cards: 'Карточки',
    contacts: 'Контакты'
  },
  help: 'Помощь',
  welcomeToVavilon: 'Добро пожаловать в Vavilon',
  pleaseLogin: 'Пожалуйста войдите в аккаунт',
  labelPleaseFillAllTheFieldsForSignUp: 'Пожалуйста заполните все поля регистрации',
  pleaseEnterTheCodeWhichIsSentOnEmail: 'Пожалуйста введите код отправленный на ящик',
  thisFieldIs: 'Поле',
  required: 'обязательно',
  login: 'Логин',
  password: 'Пароль',
  code: 'Код',
  firstName: 'Имя',
  lastName: 'Фамилия',
  email: 'Емайл',
  theEmailIs: 'Емайл',
  incorrect: 'неверный',
  minimumLengthOfPasswordIsBetween: 'и длинна пароля должна быть от 6 до 18',
  signIn: 'Войти в аккаунт',
  forgotThePassword: 'Забыли пароль?',
  signUp: 'Регистрация',
  submit: 'Отправить',
  content: 'Контент',
  priceStart: 'Минимальная цена',
  priceEnd: 'Максимальная цена',
  currencySign: 'Валюта',
  sortBy: 'Сортировка',
  direction: 'Возрастанию/Убыванию',
  search: 'Поиск',
  save: 'Сохранить',
  close: 'Закрыть',
  readyForReview: 'Готово для модерации',
  moderationStatus: 'Статус модерации',
  selectContacts: '[Выберать контакты]',
  selectAnnouncementType: '[Выберать тип объявления]',
  selectMeasure: '[Выберать объем]',
  addProduct: 'Добавить продукт',
  select: 'Выберать',
  price: 'Цена',
  selectCurrencySign: '[Выберать валюту]',
  markTerritoryForDelivery: 'Обозначте территорию для доставки',
  volume: 'Объем',
  edit: 'Изменить',
  addAnnouncement: 'Добавить объявление',
  deleteSelectedAnnouncements: 'Удалить выбранные объявления',
  addContact: 'Добавить контакты',
  deleteSelectedContacts: 'Удалить выбранные контакты',
  name: 'Имя',
  contactType: 'Тип контакта',
  value: 'Значение',
  contactDetails: 'Контактная иформация',
  contactName: 'Имя контакта',
  announcement: 'Объявление',
  sellerProfile: 'Профиль продавца',
  chat: 'Чат',
  selectModerationStatus: '[Выберать статус модерации]',
  updateModerationStatus: 'Изменить статус модерации',
  copy: 'Скопировать',
  territoryForDelivery: 'Территория доставки',
  comment: 'Комментарий',
  rated: 'Оценил',
  reply: 'Ответить',
  more: 'БОЛЬШЕ',
  messages: 'Сообщения',
  chatWith: 'Чат с',
  send: 'Отправить',
  deleteSelectedProducts: 'Удалить выбранные продукты',
  productDetails: 'Информация о продукте',
  productName: 'Имя продукта',
  selectProductCategory: '[Выбрать категорию продукта]',
  uploadImages: 'Загрузить фото',
  mainImage: 'Главная',
  delete: 'Удалить',
  info: 'Информация',
  comments: 'Комментарий',
  averageRate: 'Средняя оценка',
  announcements: 'Объявлений',
  addCard: 'Добавить карточку',
  deleteSelectedCards: 'Удалить выбранные карточки',
  action: 'Действие',
  userType: 'Тип пользователя',
  userCardDetails: 'Информация о карточке',
  cardName: 'Имя карточки',
  actionType: 'Тип действий',
  inn: 'ИНН'
}
